-- Agincourt data: products on the Campaign Builder, their uploaded
-- documents, and contacts in the Opportunity Database.
--
-- Row level security is on with no policies, so the public (anon and
-- publishable) keys can't read or write anything. Only the Agincourt server,
-- using the secret key, has access.

create table public.products (
  id text primary key check (id ~ '^p[0-9]+$'),
  name text not null,
  page_url text not null default '',
  description text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_documents (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references public.products (id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  content_type text not null default '',
  size_bytes bigint not null default 0,
  created_at timestamptz not null default now()
);

create index product_documents_product_id_idx on public.product_documents (product_id);

create table public.contacts (
  id bigint generated by default as identity primary key,
  name text not null default '',
  role text not null default '',
  company text not null default '',
  website text not null default '',
  employees text not null default '',
  industry text not null default '',
  email text not null default '',
  phone text not null default '',
  -- Ids of the products this contact already buys.
  products text[] not null default '{}',
  -- Extra spreadsheet columns, used as context by the campaign email skill.
  extra jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

create trigger contacts_set_updated_at
  before update on public.contacts
  for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.product_documents enable row level security;
alter table public.contacts enable row level security;

-- Private bucket for uploaded product documents.
insert into storage.buckets (id, name, public)
values ('product-documents', 'product-documents', false)
on conflict (id) do nothing;
