-- Launched campaigns, how each recipient engaged with the email, and the
-- business development briefings written for qualified leads.
--
-- As with the other tables, row level security is on with no policies, so
-- only the Agincourt server (secret key) can read or write.

create table public.campaigns (
  id bigint generated by default as identity primary key,
  product_id text references public.products (id) on delete set null,
  name text not null,
  launched_at timestamptz not null default now(),
  -- True for the generated demo campaign, so the UI can label it.
  is_demo boolean not null default false
);

create table public.campaign_engagements (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.campaigns (id) on delete cascade,
  contact_id bigint not null references public.contacts (id) on delete cascade,
  email_opened boolean not null default false,
  opened_at timestamptz,
  read_seconds integer not null default 0 check (read_seconds >= 0),
  clicked_through boolean not null default false,
  website_seconds integer not null default 0 check (website_seconds >= 0),
  unique (campaign_id, contact_id)
);

create index campaign_engagements_opened_idx on public.campaign_engagements (email_opened) where email_opened;

create table public.lead_briefs (
  engagement_id bigint primary key references public.campaign_engagements (id) on delete cascade,
  brief jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.campaigns enable row level security;
alter table public.campaign_engagements enable row level security;
alter table public.lead_briefs enable row level security;
